apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress
  includeCRDs: true
  repo: https://charts.konghq.com
  version: v0.13.1
  releaseName: kong-ingress
  namespace: kong-ingress
  # valuesFile: dev.values.yaml
