apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
# - argocd-notification-secret.yaml
# - argocd-dex-external-secrets.yaml
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.11.4
# - ingress.yaml
