apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
spec:
  project: default
  source:
    repoURL: https://github.com/defyjoy/kong.git
    targetRevision: main
    path: apps/rancher
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
